### ISSUE TITLE
fix Column name error 

### ISSUE THREAD

**Issue by Zuttergutao** [xinghd142857/PU-EPP#1]
In `predict.ipynb`, I think the last line in the picture below should be modified as: `df = df[df.seq.map(lambda x: len(x)<=1500)].reset_index(drop=True)`

![image](https://github.com/xinghd142857/PU-EPP/assets/40693240/62958576-b985-411e-9876-a6d9843abf4b)

**Comment by liudongliangHI** [comment]
Hello, Zuttergutao.

This is indeed our negligence. I think you're using a fasta file as an input file, but we don't have a uniform table column name for the fasta file and the csv file. Your suggestion does work when importing a fasta file, but for compatibility with CSV files (e.g. './data/example2.csv') as input, we've unified the table column names.

The bug has been fixed, thanks again for the suggestion.

```python

if PreCFG.useFasteFile:
    seq_dict = {rec.id : str(rec.seq) for rec in SeqIO.parse(PreCFG.fasteFile, "fasta")}
    mapp = {str(rec.seq):rec.id for rec in SeqIO.parse(PreCFG.fasteFile, "fasta")}
    seq = list(seq_dict.values())
    com = PreCFG.compound
    df = pd.DataFrame({'Compound':[com]*len(seq), 'Protein':seq})
else:
    df = pd.read_csv(PreCFG.csvFile)
df = df[df.Protein.map(lambda x: len(x)<=1500)].reset_index(drop=True)
```

**Comment by Zuttergutao** [comment]
Thanks！
